version: "3.8"
networks:
  site15-network:

volumes:
  site15-postgresql:


services:
  site15-postgres:
    image: "postgres:13"
    container_name: "site15-postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
    - ./env/local.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - site15-postgresql:/var/lib/postgresql/site15_data
    networks:
      - site15-network
