/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthErrorEnumInterface } from './auth-error-enum.interface';

export interface AuthErrorInterface {
  /**
   * Auth error (AUTH-000), Forbidden (AUTH-001), Unauthorized (AUTH-002)
   */
  message: string;
  code: AuthErrorEnumInterface;
  metadata?: object;
}
export namespace AuthErrorInterface {}
