/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthRoleInterface } from './auth-role.interface';

export interface AuthProfileDtoInterface {
  timezone?: number | null;
  lang?: string | null;
  userRole?: AuthRoleInterface | null;
}
export namespace AuthProfileDtoInterface {}
