/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AuthRoleInterface = 'Admin' | 'User';

export const AuthRoleInterface = {
  Admin: 'Admin' as AuthRoleInterface,
  User: 'User' as AuthRoleInterface,
};
