/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthUserScalarFieldEnumInterface } from './auth-user-scalar-field-enum.interface';

export interface AuthEntitiesInterface {
  authUser: AuthUserScalarFieldEnumInterface;
}
export namespace AuthEntitiesInterface {}
