/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthRoleInterface } from './auth-role.interface';

export interface AuthUserInterface {
  id: string;
  externalUserId: string;
  userRole: AuthRoleInterface;
  timezone: number | null;
  createdAt: string;
  updatedAt: string;
  lang: string | null;
}
export namespace AuthUserInterface {}
