/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type AuthUserScalarFieldEnumInterface =
  | 'id'
  | 'externalUserId'
  | 'userRole'
  | 'timezone'
  | 'createdAt'
  | 'updatedAt'
  | 'lang';

export const AuthUserScalarFieldEnumInterface = {
  id: 'id' as AuthUserScalarFieldEnumInterface,
  externalUserId: 'externalUserId' as AuthUserScalarFieldEnumInterface,
  userRole: 'userRole' as AuthUserScalarFieldEnumInterface,
  timezone: 'timezone' as AuthUserScalarFieldEnumInterface,
  createdAt: 'createdAt' as AuthUserScalarFieldEnumInterface,
  updatedAt: 'updatedAt' as AuthUserScalarFieldEnumInterface,
  lang: 'lang' as AuthUserScalarFieldEnumInterface,
};
