/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FilesErrorEnumInterface = 'FILES-000' | 'FILES-001';

export const FilesErrorEnumInterface = {
    FILES_000: 'FILES-000' as FilesErrorEnumInterface,
    FILES_001: 'FILES-001' as FilesErrorEnumInterface
};

