/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindManyResponseMetaInterface } from './find-many-response-meta.interface';
import { WebhookUserInterface } from './webhook-user.interface';

export interface FindManyWebhookUserResponseInterface {
  webhookUsers: Array<WebhookUserInterface>;
  meta: FindManyResponseMetaInterface;
}
