/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindManyResponseMetaInterface } from './find-many-response-meta.interface';
import { SsoRefreshSessionDtoInterface } from './sso-refresh-session-dto.interface';


export interface FindManySsoRefreshSessionResponseInterface { 
    ssoRefreshSessions: Array<SsoRefreshSessionDtoInterface>;
    meta: FindManyResponseMetaInterface;
}

