/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthUserInterface } from './auth-user.interface';
import { FindManyResponseMetaInterface } from './find-many-response-meta.interface';

export interface FindManyAuthUserResponseInterface {
  authUsers: Array<AuthUserInterface>;
  meta: FindManyResponseMetaInterface;
}
