/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoProjectDtoInterface } from './sso-project-dto.interface';
import { FindManyResponseMetaInterface } from './find-many-response-meta.interface';


export interface FindManySsoProjectResponseInterface { 
    ssoProjects: Array<SsoProjectDtoInterface>;
    meta: FindManyResponseMetaInterface;
}

