/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationsErrorMetadataInterface } from './notifications-error-metadata.interface';
import { NotificationsErrorEnumInterface } from './notifications-error-enum.interface';


export interface NotificationsErrorInterface { 
    /**
     * Notifications error (NOTIFICATIONS-000), Tenant ID not set (NOTIFICATIONS-001), User ID not set (NOTIFICATIONS-002), Forbidden (NOTIFICATIONS-003)
     */
    message: string;
    code: NotificationsErrorEnumInterface;
    metadata?: Array<NotificationsErrorMetadataInterface>;
}
export namespace NotificationsErrorInterface {
}


