/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationsEventScalarFieldEnumInterface } from './notifications-event-scalar-field-enum.interface';


export interface NotificationsEntitiesInterface { 
    notificationEvent: NotificationsEventScalarFieldEnumInterface;
}
export namespace NotificationsEntitiesInterface {
}


