/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SignUpArgsInterface { 
    email: string;
    username?: string;
    password: string;
    confirmPassword?: string;
    fingerprint: string;
    redirectUri?: string;
}

