/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SsoRefreshSessionDtoInterface {
  id: string;
  userAgent: string | null;
  userIp: string | null;
  expiresIn: number | null;
  userData: object | null;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}
