/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoUserInterface } from './sso-user.interface';
import { SsoRefreshSessionInterface } from './sso-refresh-session.interface';
import { SsoOAuthTokenInterface } from './sso-o-auth-token.interface';
import { SsoEmailTemplateInterface } from './sso-email-template.interface';


export interface SsoProjectInterface { 
    id: string;
    name: string;
    nameLocale: object | null;
    clientId: string;
    clientSecret: string;
    'public': boolean;
    createdAt: string;
    updatedAt: string;
    SsoEmailTemplate?: Array<SsoEmailTemplateInterface>;
    SsoOAuthToken_SsoOAuthToken_projectIdToSsoOAuthProvider?: Array<SsoOAuthTokenInterface>;
    SsoRefreshSession?: Array<SsoRefreshSessionInterface>;
    SsoUser?: Array<SsoUserInterface>;
}

