/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SsoOAuthTokenScalarFieldEnumInterface = 'id' | 'grantedAt' | 'accessToken' | 'refreshToken' | 'expiresAt' | 'tokenType' | 'scope' | 'verificationCode' | 'userId' | 'projectId' | 'providerId' | 'providerUserId' | 'providerUserData' | 'createdAt' | 'updatedAt';

export const SsoOAuthTokenScalarFieldEnumInterface = {
    id: 'id' as SsoOAuthTokenScalarFieldEnumInterface,
    grantedAt: 'grantedAt' as SsoOAuthTokenScalarFieldEnumInterface,
    accessToken: 'accessToken' as SsoOAuthTokenScalarFieldEnumInterface,
    refreshToken: 'refreshToken' as SsoOAuthTokenScalarFieldEnumInterface,
    expiresAt: 'expiresAt' as SsoOAuthTokenScalarFieldEnumInterface,
    tokenType: 'tokenType' as SsoOAuthTokenScalarFieldEnumInterface,
    scope: 'scope' as SsoOAuthTokenScalarFieldEnumInterface,
    verificationCode: 'verificationCode' as SsoOAuthTokenScalarFieldEnumInterface,
    userId: 'userId' as SsoOAuthTokenScalarFieldEnumInterface,
    projectId: 'projectId' as SsoOAuthTokenScalarFieldEnumInterface,
    providerId: 'providerId' as SsoOAuthTokenScalarFieldEnumInterface,
    providerUserId: 'providerUserId' as SsoOAuthTokenScalarFieldEnumInterface,
    providerUserData: 'providerUserData' as SsoOAuthTokenScalarFieldEnumInterface,
    createdAt: 'createdAt' as SsoOAuthTokenScalarFieldEnumInterface,
    updatedAt: 'updatedAt' as SsoOAuthTokenScalarFieldEnumInterface
};

