/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoRefreshSessionScalarFieldEnumInterface } from './sso-refresh-session-scalar-field-enum.interface';
import { SsoRoleInterface } from './sso-role.interface';
import { SsoOAuthTokenScalarFieldEnumInterface } from './sso-o-auth-token-scalar-field-enum.interface';
import { SsoProjectScalarFieldEnumInterface } from './sso-project-scalar-field-enum.interface';
import { SsoEmailTemplateScalarFieldEnumInterface } from './sso-email-template-scalar-field-enum.interface';
import { SsoUserScalarFieldEnumInterface } from './sso-user-scalar-field-enum.interface';
import { SsoOAuthProviderScalarFieldEnumInterface } from './sso-o-auth-provider-scalar-field-enum.interface';
import { SsoOAuthProviderSettingsScalarFieldEnumInterface } from './sso-o-auth-provider-settings-scalar-field-enum.interface';


export interface SsoEntitiesInterface { 
    SsoProject: SsoProjectScalarFieldEnumInterface;
    SsoUser: SsoUserScalarFieldEnumInterface;
    SsoRefreshSession: SsoRefreshSessionScalarFieldEnumInterface;
    SsoEmailTemplate: SsoEmailTemplateScalarFieldEnumInterface;
    SsoOAuthProvider: SsoOAuthProviderScalarFieldEnumInterface;
    SsoOAuthProviderSettings: SsoOAuthProviderSettingsScalarFieldEnumInterface;
    SsoOAuthToken: SsoOAuthTokenScalarFieldEnumInterface;
    role: SsoRoleInterface;
}
export namespace SsoEntitiesInterface {
}


