/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SsoProjectScalarFieldEnumInterface = 'id' | 'name' | 'nameLocale' | 'clientId' | 'clientSecret' | 'public' | 'createdAt' | 'updatedAt';

export const SsoProjectScalarFieldEnumInterface = {
    id: 'id' as SsoProjectScalarFieldEnumInterface,
    name: 'name' as SsoProjectScalarFieldEnumInterface,
    nameLocale: 'nameLocale' as SsoProjectScalarFieldEnumInterface,
    clientId: 'clientId' as SsoProjectScalarFieldEnumInterface,
    clientSecret: 'clientSecret' as SsoProjectScalarFieldEnumInterface,
    public: 'public' as SsoProjectScalarFieldEnumInterface,
    createdAt: 'createdAt' as SsoProjectScalarFieldEnumInterface,
    updatedAt: 'updatedAt' as SsoProjectScalarFieldEnumInterface
};

