/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SsoProjectDtoInterface { 
    id: string;
    name: string;
    nameLocale: object | null;
    clientId: string;
    clientSecret: string;
    'public': boolean;
    createdAt: string;
    updatedAt: string;
}

