/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoUserInterface } from './sso-user.interface';

export interface SsoTwoFactorCodeInterface {
  id: string;
  userId: string;
  operationName: string;
  code: string;
  type: string;
  maxAttempt: number;
  attempt: number;
  timeout: number;
  used: boolean;
  createdAt: string;
  updatedAt: string;
  SsoUser?: SsoUserInterface;
}
