/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SsoUserDtoInterface { 
    id: string;
    email: string;
    phone: string | null;
    username: string | null;
    roles: string | null;
    firstname: string | null;
    lastname: string | null;
    gender: string | null;
    birthdate: string | null;
    picture: string | null;
    appData: object | null;
    revokedAt: string | null;
    emailVerifiedAt: string | null;
    phoneVerifiedAt: string | null;
    timezone: number | null;
    lang: string | null;
    createdAt: string;
    updatedAt: string;
}

