/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SsoUserDtoInterface {
  id: string;
  email: string;
  username: string | null;
  password: string;
  roles: string | null;
  firstname: string | null;
  lastname: string | null;
  birthdate: string | null;
  picture: string | null;
  appData: object | null;
  createdAt: string;
  updatedAt: string;
}
