/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type SsoUserScalarFieldEnumInterface =
  | 'id'
  | 'email'
  | 'username'
  | 'password'
  | 'roles'
  | 'firstname'
  | 'lastname'
  | 'birthdate'
  | 'picture'
  | 'appData'
  | 'projectId'
  | 'createdAt'
  | 'updatedAt';

export const SsoUserScalarFieldEnumInterface = {
  id: 'id' as SsoUserScalarFieldEnumInterface,
  email: 'email' as SsoUserScalarFieldEnumInterface,
  username: 'username' as SsoUserScalarFieldEnumInterface,
  password: 'password' as SsoUserScalarFieldEnumInterface,
  roles: 'roles' as SsoUserScalarFieldEnumInterface,
  firstname: 'firstname' as SsoUserScalarFieldEnumInterface,
  lastname: 'lastname' as SsoUserScalarFieldEnumInterface,
  birthdate: 'birthdate' as SsoUserScalarFieldEnumInterface,
  picture: 'picture' as SsoUserScalarFieldEnumInterface,
  appData: 'appData' as SsoUserScalarFieldEnumInterface,
  projectId: 'projectId' as SsoUserScalarFieldEnumInterface,
  createdAt: 'createdAt' as SsoUserScalarFieldEnumInterface,
  updatedAt: 'updatedAt' as SsoUserScalarFieldEnumInterface,
};
