/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoUserInterface } from './sso-user.interface';

export interface SsoRefreshSessionInterface {
  id: string;
  refreshToken: string;
  userAgent: string | null;
  fingerprint: string | null;
  userIp: string | null;
  expiresIn: number | null;
  userId: string;
  createdAt: string;
  updatedAt: string;
  SsoUser?: SsoUserInterface;
}
