/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoUserInterface } from './sso-user.interface';

export interface SsoProjectInterface {
  id: string;
  clientId: string;
  clientSecret: string;
  createdAt: string;
  updatedAt: string;
  SsoUser?: Array<SsoUserInterface>;
}
