/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type SsoProjectScalarFieldEnumInterface =
  | 'id'
  | 'clientId'
  | 'clientSecret'
  | 'createdAt'
  | 'updatedAt';

export const SsoProjectScalarFieldEnumInterface = {
  id: 'id' as SsoProjectScalarFieldEnumInterface,
  clientId: 'clientId' as SsoProjectScalarFieldEnumInterface,
  clientSecret: 'clientSecret' as SsoProjectScalarFieldEnumInterface,
  createdAt: 'createdAt' as SsoProjectScalarFieldEnumInterface,
  updatedAt: 'updatedAt' as SsoProjectScalarFieldEnumInterface,
};
