/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SsoEmailTemplateScalarFieldEnumInterface = 'id' | 'subject' | 'subjectLocale' | 'text' | 'textLocale' | 'html' | 'htmlLocale' | 'operationName' | 'projectId' | 'createdAt' | 'updatedAt';

export const SsoEmailTemplateScalarFieldEnumInterface = {
    id: 'id' as SsoEmailTemplateScalarFieldEnumInterface,
    subject: 'subject' as SsoEmailTemplateScalarFieldEnumInterface,
    subjectLocale: 'subjectLocale' as SsoEmailTemplateScalarFieldEnumInterface,
    text: 'text' as SsoEmailTemplateScalarFieldEnumInterface,
    textLocale: 'textLocale' as SsoEmailTemplateScalarFieldEnumInterface,
    html: 'html' as SsoEmailTemplateScalarFieldEnumInterface,
    htmlLocale: 'htmlLocale' as SsoEmailTemplateScalarFieldEnumInterface,
    operationName: 'operationName' as SsoEmailTemplateScalarFieldEnumInterface,
    projectId: 'projectId' as SsoEmailTemplateScalarFieldEnumInterface,
    createdAt: 'createdAt' as SsoEmailTemplateScalarFieldEnumInterface,
    updatedAt: 'updatedAt' as SsoEmailTemplateScalarFieldEnumInterface
};

