/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SsoOAuthProviderScalarFieldEnumInterface = 'id' | 'name' | 'createdAt' | 'updatedAt';

export const SsoOAuthProviderScalarFieldEnumInterface = {
    id: 'id' as SsoOAuthProviderScalarFieldEnumInterface,
    name: 'name' as SsoOAuthProviderScalarFieldEnumInterface,
    createdAt: 'createdAt' as SsoOAuthProviderScalarFieldEnumInterface,
    updatedAt: 'updatedAt' as SsoOAuthProviderScalarFieldEnumInterface
};

