/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SsoRoleInterface = 'admin' | 'manager' | 'user';

export const SsoRoleInterface = {
    admin: 'admin' as SsoRoleInterface,
    manager: 'manager' as SsoRoleInterface,
    user: 'user' as SsoRoleInterface
};

