/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoProjectScalarFieldEnumInterface } from './sso-project-scalar-field-enum.interface';
import { SsoUserScalarFieldEnumInterface } from './sso-user-scalar-field-enum.interface';

export interface SsoEntitiesInterface {
  ssoProject: SsoProjectScalarFieldEnumInterface;
  ssoUser: SsoUserScalarFieldEnumInterface;
}
export namespace SsoEntitiesInterface {}
