/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TerminusHealthCheckControllerCheck200ResponseInfoValueInterface } from './terminus-health-check-controller-check200-response-info-value.interface';


export interface TerminusHealthCheckControllerCheck200ResponseInterface { 
    status?: string;
    info?: { [key: string]: TerminusHealthCheckControllerCheck200ResponseInfoValueInterface; } | null;
    error?: { [key: string]: TerminusHealthCheckControllerCheck200ResponseInfoValueInterface; } | null;
    details?: { [key: string]: TerminusHealthCheckControllerCheck200ResponseInfoValueInterface; };
}

