/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TwoFactorErrorMetadataConstraintInterface } from './two-factor-error-metadata-constraint.interface';


export interface TwoFactorErrorMetadataInterface { 
    property: string;
    constraints: Array<TwoFactorErrorMetadataConstraintInterface>;
    children?: Array<TwoFactorErrorMetadataInterface>;
}

