/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TwoFactorErrorEnumInterface = 'TWO_FACTOR-000' | 'TWO-FACTOR-001' | 'TWO-FACTOR-002' | 'TWO-FACTOR-003' | 'TWO-FACTOR-004' | 'TWO-FACTOR-005';

export const TwoFactorErrorEnumInterface = {
    TWO_FACTOR_000: 'TWO_FACTOR-000' as TwoFactorErrorEnumInterface,
    TWO_FACTOR_001: 'TWO-FACTOR-001' as TwoFactorErrorEnumInterface,
    TWO_FACTOR_002: 'TWO-FACTOR-002' as TwoFactorErrorEnumInterface,
    TWO_FACTOR_003: 'TWO-FACTOR-003' as TwoFactorErrorEnumInterface,
    TWO_FACTOR_004: 'TWO-FACTOR-004' as TwoFactorErrorEnumInterface,
    TWO_FACTOR_005: 'TWO-FACTOR-005' as TwoFactorErrorEnumInterface
};

