/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TwoFactorErrorMetadataInterface } from './two-factor-error-metadata.interface';
import { TwoFactorErrorEnumInterface } from './two-factor-error-enum.interface';


export interface TwoFactorErrorInterface { 
    /**
     * Two factor error (TWO_FACTOR-000), Two factor code not set (TWO-FACTOR-001), Wrong two factor code (TWO-FACTOR-002), Two factor code is outdated (TWO-FACTOR-003), Please wait 30 seconds (TWO-FACTOR-004), Two-factor code has already been used (TWO-FACTOR-005)
     */
    message: string;
    code: TwoFactorErrorEnumInterface;
    metadata?: Array<TwoFactorErrorMetadataInterface>;
}
export namespace TwoFactorErrorInterface {
}


