/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebhookRoleInterface } from './webhook-role.interface';

export interface UpdateWebhookUserDtoInterface {
  externalTenantId?: string;
  externalUserId?: string;
  userRole?: WebhookRoleInterface;
}
export namespace UpdateWebhookUserDtoInterface {}
