/**
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateProfileModelInterface {
  email: string;
  username: string | null;
  password: string;
  firstname: string | null;
  lastname: string | null;
  birthdate: string | null;
  picture: string | null;
}
