/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProfileArgsInterface { 
    firstname?: string | null;
    lastname?: string | null;
    gender?: string | null;
    birthdate?: string | null;
    picture?: string | null;
    timezone?: number | null;
    lang?: string | null;
    oldPassword?: string;
    password?: string;
    confirmPassword?: string;
}

