/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateWebhookDtoInterface { 
    eventName?: string;
    endpoint?: string;
    enabled?: boolean;
    headers?: object | null;
    requestTimeout?: number | null;
    workUntilDate?: string | null;
}

