/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSsoProjectDtoInterface { 
    name?: string;
    clientId?: string;
    clientSecret?: string;
    'public'?: boolean;
}

