/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebhookStatusInterface } from './webhook-status.interface';


export interface WebhookTestRequestResponseInterface { 
    request: object;
    responseStatus: string;
    response: object | null;
    webhookStatus: WebhookStatusInterface;
}
export namespace WebhookTestRequestResponseInterface {
}


