/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WebhookErrorEnumInterface = 'WEBHOOK-000' | 'WEBHOOK-001' | 'WEBHOOK-002' | 'WEBHOOK-003' | 'WEBHOOK-004' | 'WEBHOOK-005';

export const WebhookErrorEnumInterface = {
    WEBHOOK_000: 'WEBHOOK-000' as WebhookErrorEnumInterface,
    WEBHOOK_001: 'WEBHOOK-001' as WebhookErrorEnumInterface,
    WEBHOOK_002: 'WEBHOOK-002' as WebhookErrorEnumInterface,
    WEBHOOK_003: 'WEBHOOK-003' as WebhookErrorEnumInterface,
    WEBHOOK_004: 'WEBHOOK-004' as WebhookErrorEnumInterface,
    WEBHOOK_005: 'WEBHOOK-005' as WebhookErrorEnumInterface
};

