version: '3'
networks:
  site15-network:
    driver: 'bridge'
services:
  site15-postgre-sql:
    image: 'postgres:15.10'
    container_name: 'site15-postgre-sql'
    networks:
      - 'site15-network'
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U $$POSTGRES_USER'
      interval: '5s'
      timeout: '5s'
      retries: 5
    tty: true
    restart: 'always'
    environment:
      POSTGRES_USER: '%SITE_15_POSTGRE_SQL_POSTGRESQL_USERNAME%'
      POSTGRES_PASSWORD: '%SITE_15_POSTGRE_SQL_POSTGRESQL_PASSWORD%'
      POSTGRES_DB: '%SITE_15_POSTGRE_SQL_POSTGRESQL_DATABASE%'
    volumes:
      - 'site15-postgre-sql-volume:/var/lib/postgresql/data'
volumes:
  site15-postgre-sql-volume:
    name: 'site15-postgre-sql-volume'
