FROM node:14-alpine
LABEL maintainer="admin@site15.ru"
WORKDIR /usr/src/app
COPY ./apps/site15-backend/package.json ./
COPY ./prisma/schema.prisma ./
RUN npm config set package-lock false
RUN npm i --only=production
RUN npm run generate
COPY ./dist/apps/site15-backend .
EXPOSE 5000
STOPSIGNAL SIGINT
CMD ["node", "main.js"]