apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '%NAMESPACE%'
  name: %NAMESPACE%-server-config
data:
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
  SITE_15_PORT: '%SITE_15_PORT%'
  SITE_15_ROOT_DATABASE_URL: 'postgres://%SITE_15_POSTGRE_SQL_POSTGRESQL_USERNAME%:%SITE_15_POSTGRE_SQL_POSTGRESQL_PASSWORD%@10.0.1.1:5432/%SITE_15_POSTGRE_SQL_POSTGRESQL_DATABASE%?schema=public'
  SITE_15_WEBHOOK_DATABASE_URL: 'postgres://%SITE_15_WEBHOOK_DATABASE_USERNAME%:%SITE_15_WEBHOOK_DATABASE_PASSWORD%@10.0.1.1:5432/%SITE_15_WEBHOOK_DATABASE_NAME%?schema=public'
  SITE_15_SSO_DATABASE_URL: 'postgres://%SITE_15_SSO_DATABASE_USERNAME%:%SITE_15_SSO_DATABASE_PASSWORD%@10.0.1.1:5432/%SITE_15_SSO_DATABASE_NAME%?schema=public'
  SITE_15_METRICS_DATABASE_URL: 'postgres://%SITE_15_METRICS_DATABASE_USERNAME%:%SITE_15_METRICS_DATABASE_PASSWORD%@10.0.1.1:5432/%SITE_15_METRICS_DATABASE_NAME%?schema=public'
  SITE_15_NOTIFICATIONS_DATABASE_URL: 'postgres://%SITE_15_NOTIFICATIONS_DATABASE_USERNAME%:%SITE_15_NOTIFICATIONS_DATABASE_PASSWORD%@10.0.1.1:5432/%SITE_15_NOTIFICATIONS_DATABASE_NAME%?schema=public'
  SITE_15_TWO_FACTOR_DATABASE_URL: 'postgres://%SITE_15_TWO_FACTOR_DATABASE_USERNAME%:%SITE_15_TWO_FACTOR_DATABASE_PASSWORD%@10.0.1.1:5432/%SITE_15_TWO_FACTOR_DATABASE_NAME%?schema=public'
  SITE_15_SSO_ADMIN_EMAIL: '%SITE_15_SSO_ADMIN_EMAIL%'
  SITE_15_SSO_ADMIN_USERNAME: '%SITE_15_SSO_ADMIN_USERNAME%'
  SITE_15_SSO_ADMIN_PASSWORD: '%SITE_15_SSO_ADMIN_PASSWORD%'
  SITE_15_SSO_ADMIN_SECRET: '%SITE_15_SSO_ADMIN_SECRET%'
  SITE_15_MINIO_SERVER_HOST: '%NAMESPACE%-minio.%NAMESPACE%'
  SITE_15_MINIO_ACCESS_KEY: '%SITE_15_MINIO_MINIO_ROOT_USER%'
  SITE_15_MINIO_SECRET_KEY: '%SITE_15_MINIO_MINIO_ROOT_PASSWORD%'
  SITE_15_KEYV_URL: 'redis://:%SITE_15_REDIS_REDIS_PASSWORD%@%NAMESPACE%-redis.%NAMESPACE%:6379'
  SITE_15_CLIENT_MINIO_URL: 'https://files.%SITE_15_DOMAIN%'
  SITE_15_SSO_CLIENT_URL: 'https://%SITE_15_DOMAIN%'
  SITE_15_SSO_SERVER_URL: 'https://%SITE_15_DOMAIN%'
  SITE_15_SSO_GOOGLE_OAUTH_CLIENT_ID: '%SITE_15_SSO_GOOGLE_OAUTH_CLIENT_ID%'
  SITE_15_SSO_GOOGLE_OAUTH_CLIENT_SECRET_KEY: '%SITE_15_SSO_GOOGLE_OAUTH_CLIENT_SECRET_KEY%'
  SITE_15_SSO_DEFAULT_PUBLIC_TENANTS: '%SITE_15_SSO_DEFAULT_PUBLIC_TENANTS%'
  SITE_15_SSO_DEFAULT_TENANT: '%SITE_15_SSO_DEFAULT_TENANT%'
  SITE_15_NOTIFICATIONS_MAIL_TRANSPORT: '%SITE_15_NOTIFICATIONS_MAIL_TRANSPORT%'
  SITE_15_NOTIFICATIONS_MAIL_DEFAULT_SENDER_NAME: '%SITE_15_NOTIFICATIONS_MAIL_DEFAULT_SENDER_NAME%'
  SITE_15_NOTIFICATIONS_MAIL_DEFAULT_SENDER_EMAIL: '%SITE_15_NOTIFICATIONS_MAIL_DEFAULT_SENDER_EMAIL%'
