/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationsEventDtoInterface { 
    id: string;
    type: string;
    operationName: string;
    subject: string;
    html: string;
    text: string | null;
    attempt: number;
    used: boolean;
    error: object | null;
    senderData: object | null;
    recipientGroupId: string;
    recipientData: object | null;
    externalTenantId: string;
    createdAt: string;
    updatedAt: string;
}

