/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuthProviderInterface { 
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    url: string;
}

