/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoProjectInterface } from './sso-project.interface';


export interface SsoEmailTemplateInterface { 
    id: string;
    subject: string;
    subjectLocale: object | null;
    text: string;
    textLocale: object | null;
    html: string;
    htmlLocale: object | null;
    operationName: string | null;
    projectId: string;
    createdAt: string;
    updatedAt: string;
    SsoProject?: SsoProjectInterface;
}

