/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoUserInterface } from './sso-user.interface';
import { SsoProjectInterface } from './sso-project.interface';


export interface SsoRefreshSessionInterface { 
    id: string;
    userAgent: string | null;
    userIp: string | null;
    expiresAt: string | null;
    userData: object | null;
    enabled: boolean;
    userId: string;
    projectId: string;
    createdAt: string;
    updatedAt: string;
    SsoProject?: SsoProjectInterface;
    SsoUser?: SsoUserInterface;
}

