/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SsoOAuthTokenInterface } from './sso-o-auth-token.interface';
import { SsoOAuthProviderSettingsInterface } from './sso-o-auth-provider-settings.interface';


export interface SsoOAuthProviderInterface { 
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    SsoOAuthProviderSettings?: Array<SsoOAuthProviderSettingsInterface>;
    SsoOAuthToken?: Array<SsoOAuthTokenInterface>;
}

