/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SsoRefreshSessionScalarFieldEnumInterface = 'id' | 'refreshToken' | 'userAgent' | 'fingerprint' | 'userIp' | 'expiresAt' | 'userData' | 'enabled' | 'userId' | 'projectId' | 'createdAt' | 'updatedAt';

export const SsoRefreshSessionScalarFieldEnumInterface = {
    id: 'id' as SsoRefreshSessionScalarFieldEnumInterface,
    refreshToken: 'refreshToken' as SsoRefreshSessionScalarFieldEnumInterface,
    userAgent: 'userAgent' as SsoRefreshSessionScalarFieldEnumInterface,
    fingerprint: 'fingerprint' as SsoRefreshSessionScalarFieldEnumInterface,
    userIp: 'userIp' as SsoRefreshSessionScalarFieldEnumInterface,
    expiresAt: 'expiresAt' as SsoRefreshSessionScalarFieldEnumInterface,
    userData: 'userData' as SsoRefreshSessionScalarFieldEnumInterface,
    enabled: 'enabled' as SsoRefreshSessionScalarFieldEnumInterface,
    userId: 'userId' as SsoRefreshSessionScalarFieldEnumInterface,
    projectId: 'projectId' as SsoRefreshSessionScalarFieldEnumInterface,
    createdAt: 'createdAt' as SsoRefreshSessionScalarFieldEnumInterface,
    updatedAt: 'updatedAt' as SsoRefreshSessionScalarFieldEnumInterface
};

