/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSsoEmailTemplateDtoInterface { 
    subject?: string;
    subjectLocale?: object | null;
    text?: string;
    textLocale?: object | null;
    html?: string;
    htmlLocale?: object | null;
    operationName?: string | null;
}

